### ISSUE TITLE
[optin/reporting]: List of completed opt-ins

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/product#47]
The opt-in reporting tool should present all completed (paid requests from pre-launch and post-launch) opt-ins.

I. The list of completed opt-ins should contain the following columns:

a) "Type" - "PRE" - for pre-launch, "POST" - for post-launch
b) "Label" - additional info about NEM address "label" e.g. "Binance"
c) "NEM Address" - in a single row can be multiple addresses for opt-in type 'merge' and 'multi'. Address should link to explorer https://explorer.nemtool.com. There should be an option to easy copy address.
d) "Hash":
NEM transaction hashes
- if there is no on-chain opt-in we show "off-chain"
- otherwise, we show a list (which can be multiple for each NEM address in case of multisig) of hashes related to the address. Each hash is preceded by a timestamp (presented based on local browser timezone)
There should be an option to easy copy hash.
e) "Balance" - balance for each NEM address. If we have multiple entries per row we should show bolded the sum in an additional row.
f) "Symbol Address"  - in a single row can be multiple addresses for opt-in type 'merge' and 'multi'. Should be linked to https://symbol.fyi/. There should be an option to easy copy address.
g) "Hash" - Symbol transaction payout hashes. Each hash is preceded by a timestamp (presented based on local browser timezone). There should be an option to easy copy hash.
h) "Balance" - balance for each Symbol address. If we have multiple entries we should show the sum below.

On top of the screen should be an option to:
- Search by NEM/Symbol address/Hash (one input).
- export data to CSV
- filter by opt-in type (pre-launch, post-launch)

Pagination: 200 elements per page. Infinite scroll.
Order: We should order descending by opt-in id

2. Wireframe:
![Completed_list_view](https://user-images.githubusercontent.com/17684281/163791720-a20668e8-9eb1-449a-bd74-2d6e578335f5.png)

3. CSV columns:
a) # - opt-in number e.g. "1"
b) "Type" - Post-launch or Pre-launch
c) "Label" - e.g. "Binance"
d) "NEM Address" e.g. "NATRUSTUAB5LAWDSOWDUPQUFYRTGZTJZDGML2JKP"
e) "Height" - NEM transaction height - if we have multiple opt-in tx for NEM address (multisig) we should export latests. 
f) "Hash" "18b358c9fb99469614e6b5f3114e911c0ec14e656126db55209daed59a9451a2" - if multiple then comma separated
g) "Timestamp" e.g. "2010-12-11 12:02:53" - if we have multiple opt-in tx for NEM address (multisig) we should export latests. Timestamp in user local time.
h) "Timestamp UTC" e.g. "2010-12-11 14:02:53" - UTC timestamp for NEM transaction
i) "Balance" e.g. "99584654.050913"
j) "Symbol Address" e.g. "NCIG65BEOUJPH2AP7ELHOPYIH7FANQEH5CCOBEI"
k) "Height" - Symbol payout transaction height
l) "Hash" Symbol hash e.g. "e24ed6ae1591353e2515940b18d1b0f5eb233f4544d2630d8fdd6a1923235a8b"
m) "Timestamp" e.g. "2010-12-11 12:02:53" - timestamp for Symbol transaction. Timestamp in user local time.
n) "Timestamp UTC" -  UTC timestamp for Symbol transaction
o) "Balance" - Symbol tx balance  e.g. "9584654.150913"

Example CSV:
[optin-completed.csv](https://github.com/symbol/product/files/8516056/optin-completed.csv)

Completed DB:
[completed.zip](https://github.com/symbol/product/files/8520417/completed.zip)

**Comment by 0x6861746366574** [comment]
Looks good, @cryptoBeliever!

**UX/UI** 

* Always capitalize the first letter of each word in a title. For example, `NEM address` should be `NEM Address`. 
* Change the header of `NEM opt-in transactions` and `Symbol payout transactions` to 'Hash'. 
* `NEM Balance` and `Symbol balance` can read 'Balance'.
* Remove the `Total` text in the Address column, and instead add a border around the Total in the Balance column. 
* For the front-end, make sure to format the numbers according to the accounting standard: two decimal points; a thousands separator (For example, 100000 becomes 100,000.00) and negative numbers are displayed in parentheses. When downloading to .csv, numbers should be displayed in absolute. 
* For pagination, I'd not display tabs but instead allow for endless scrolling. Start with 1000 entries loaded, and then allow to scroll (sorted by timestamp).

**Labelling** 

* We will want to have an additional column that labels off-chain addresses (for example, Binance or Huobi) and known accounts (for example, the old NATRUST NEM account and its subsequent Symbol accounts would all be labelled NEM Group Trust). 
* You'll want to make sure the exported `Hash` provides a link to the explorer. 
* You will want an additional column for 'timestamp' - not _as_ important for pre-launch transactions, but pretty critical for the postlaunch ones.

**Comment by cryptoBeliever** [comment]
> We will want to have an additional column that labels off-chain addresses (for example, Binance or Huobi) and known accounts (for example, the old NATRUST NEM account and its subsequent Symbol accounts would all be labeled NEM Group Trust).

@0x6861746366574, @gimre-xymcity commented on that- all exchanges are opt-in on-chain. That off-chain are Trust and some private devs' addresses. Do we want to label them? I think in such a case @gimre-xymcity has to add it too into DB or we can hardcode it to CSV export (since it will not change and it's only for pre-launch).

> You will want an additional column for 'timestamp' - not as important for pre-launch transactions, but pretty critical for the postlaunch ones.

@0x6861746366574 Is this payment timestamp on Symbol chain or NEM opt-in chain timestamp?

**Comment by 0x6861746366574** [comment]
> @0x6861746366574, @gimre-xymcity commented on that- all exchanges are opt-in on-chain. That off-chain are Trust and some private devs' addresses. Do we want to label them? I think in such a case @gimre-xymcity has to add it too into DB or we can hardcode it to CSV export (since it will not change and it's only for pre-launch).

Yep, we'll want to label these.

> @0x6861746366574 Is this payment timestamp on Symbol chain or NEM opt-in chain timestamp?

Ah, good point. You'll want to record both the `request` timestamp (when the request was initiated on NEM), as well as the `payout` timestamp (when funds were sent to the user on Symbol).

**Comment by yilmazbahadir** [comment]
@0x6861746366574 What type of user wants to see the whole list? (Considering we have search and the CSV export functionalities in place)
> For pagination, I'd not display tabs but instead allow for endless scrolling. Start with 1000 entries loaded, and then allow to scroll (sorted by timestamp).

**Comment by 0x6861746366574** [comment]
> @0x6861746366574 What type of user wants to see the whole list? (Considering we have search and the CSV export functionalities in place)

It's not a type of user, just a UX pattern to follow. Modern UX has us scroll or pull down to load more results - think about how Twitter, TikTok, etc. all work. 

Pages were very much a UX pattern in the 00's and 10's but have slowly been replaced by _doomscrolling_. You can see an example of the 'doomscroll' here: https://solanabeach.io/transactions - although, it requires you to click _load more_ which is undesirable UX. You'd typically want to load up 1000 records and then when you scroll to the end of the page automatically load more (much like Twitter).

**Comment by cryptoBeliever** [comment]
Found issues (http://ec2-35-171-24-22.compute-1.amazonaws.com:5001/):
(-) Enter should call Search action when focus in search input.
(-) The copy button doesn't work
(-) When I search address with whitespace e.g. ' NCES7OKBYZRCSTSNRX45H6E67J6OXABKNT6IRD2P' nothing is filtered. Missing trim before using it in a query?
(-) when I put the lowercase address in the search bar and will search the result is a blank page e.g. nanodestsn7gu76qplgmj7bcgcaa2phvbzzuui62
(-) we can replace Opt-in Type to label as we have on pending view in the status column
(-) problems with mobile view presentation and scaling
(-) can we detect there is no more pages and don't try to load more? For example filter by "NANODESTSN7GU76QPLGMJ7BCGCAA2PHVBZZUUI62" and when we scroll we trying load more.
(-) search-header is shorter than the table header

**Comment by cryptoBeliever** [comment]
All done.
